version: "3.8"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # volumes:
    #   - .:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mongo:latest
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env

volumes:
  mongodb_data:
    driver: local
