version: '3.8'

services:
  pocketbase:
    build: .
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/app/pb_data
    environment:
      POCKETBASE_ADMIN_EMAIL: admin@example.com
      POCKETBASE_ADMIN_PASSWORD: secret
    command: ["./pocketbase", "serve", "--http=0.0.0.0:8090"]
